### ISSUE TITLE
Cleanup first (.idea & uneeded artifacts)

### ISSUE THREAD

**Issue by mariusrugan** [bjornharvold/bearchoke#5]
I've branched to develop.
https://github.com/MariusRugan/bearchoke/tree/develop
please take a look at .gitignore and if needed point out .idea files that should be kept.

**Comment by bjornharvold** [comment]
Hi Marius,

I actually found developers get up and running more quickly if the project
files are already there. I even checked in all node modules for the
front-end app as well.

If you're using IntelliJ and you didn't find that to be the case we can
definitely remove them. It's all about how easy you can get the project set
up.

On Wednesday, February 18, 2015, Marius Rugan notifications@github.com
wrote:

> I've branched to develop.
> https://github.com/MariusRugan/bearchoke/tree/develop
> please take a look at .gitignore and if needed point out .idea files that
> should be kept.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/bjornharvold/bearchoke/issues/5.

## 

Cheers,
Bjorn

---

_Bjorn Harvold_
_E-mail_: bjorn@harvold.com
_U.S. Mobile_: +1-917-494-6357
_Google Voice_: +1-917-934-3912
_Skype_: +1-917-720-3351 / bjornharvold
_Thai Mobile_: +66-85151-0325
_Facebook_: bjornharvold
_Twitter_: @bjornharvold
_LinkedIn_: bjornharvold

**Comment by bjornharvold** [comment]
All unnecessary project files have been removed
